#!/bin/sh
#SBATCH -A TG-AST140041
#SBATCH -J avg_MF_cov_conv
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p skx
#SBATCH -t 2:00:00
#SBATCH -o /scratch/07833/tg871330/tSZ_NG_ini_jobs/job_files_suite/avg_stat/output_files/avg_MF_cov_conv.o%j
#SBATCH --mail-user=a.sabyr@columbia.edu
#SBATCH --mail-type=all

source /home1/07833/tg871330/miniconda3/bin/activate tSZ


for i in {3456..34560..3456}

do
    python /scratch/07833/tg871330/tSZ_NG/code/suite_code/compute_covariance_nsims.py 20bin_1to3sigma_MF 60 MF_V0_V1_V2 20bin_1to3sigma 1 $i

done
