#!/bin/sh
#SBATCH -A TG-AST140041
#SBATCH -J avg_all_goal_wiener_beam_final
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p skx
#SBATCH -t 6:00:00
#SBATCH -o /scratch/07833/tg871330/tSZ_NG_ini_jobs/job_files_suite/avg_stat/output_files/avg_all.o%j
#SBATCH --mail-user=a.sabyr@columbia.edu
#SBATCH --mail-type=all

source /home1/07833/tg871330/miniconda3/bin/activate tSZ
python /scratch/07833/tg871330/tSZ_NG/code/suite_code/compute_avg_suite.py noise_goal_beam_cl,9bins_goal_wiener_beam_peaks,30bin_3to3_goal_wiener_beam_MF,7bins_goal_wiener_beam_minima,goal_wiener_full_beam_moments 192 cl_peaks_MF_V0_V1_V2_minima_moments_sigma0_sigma1_S0_S1_S2_K0_K1_K2_K3 all_goal_wiener_beam_final 1 30
